# -*- coding: utf-8 -*-
"""sorting_algo_practice_chp2-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVD4V5CbrKoBiaS1ZUbn7UiXgvq50Nc9
"""

# @title
List_A = [3, 4, 7, 1, 3]

def insertion_sort_asc(list):

    for i in range(1, len(list)):
        key = list[i]
        j = i - 1
        while j >= 0 and list[j] > key:
            list[j + 1] = list[j]
            j = j - 1

        list[j + 1] = key

    return list

insertion_sort_asc(List_A)

# @title
List_B = [4, 3, 7, 8, 9, 22, 54, 1, 2, 4, 5]

def insertion_sort_desc(list):
  for i in range(1, len(list)):
    key = list[i]
    j = i - 1

    while j >= 0 and list[j] < key:
      list[j + 1] = list[j]
      j = j - 1

    list[j + 1] = key

  return list


insertion_sort_desc(List_B)

# @title
List_C = [3, 2, 55, 7, 8, 9, 22, 1, 1]

def insertion_sort_asc_b(list):
  for i in range(1, len(list)):
    key = list[i]
    j = i - 1

    while j >= 0 and list[j] > key:
      list[j + 1] = list[j]
      j = j - 1

    list[j + 1] = key

  return list


insertion_sort_asc_b(List_B)

# @title
def insertion_sort_asc_c(list):
  for i in range(1, len(list)):
    key = list[i]
    j = i - 1
    while j <= 0 and list[j] > key:
      list[j + 1] = list[j]
      j = j - 1

    list[j + 1] = key
  return list


insertion_sort_asc_c(List_C)

# @title
def linear_search(numbers, target):
  for i in range(len(numbers)):
    if numbers[i] == target:
      return i
  return None

# @title
bin1 = [1, 0, 1, 1, 1, 0, 1]
bin2 = [1, 1, 1, 0, 0]

def add_two_binarynumber(num1, num2):
  exponent1 = 0
  sum1 = 0
  for i in range(len(num1) - 1, -1, -1):
    sum1 += num1[i] * (2 ** exponent1)
    exponent1 += 1

  exponent2 = 0
  sum2 = 0
  for j in range(len(num2) - 1, -1, -1):
    sum2 += num2[j] * (2 ** exponent2)
    exponent2 += 1

  return sum1 + sum2


add_two_binarynumber(bin1, bin2)

# @title
def selection_sort_smallest(list):

  for i in range(len(list)):

    smallest_index = i

    for j in range(i + 1, len(list)):
      if list[j] < list[smallest_index]:
        smallest_index = j

    temp = list[i]
    list[i] = list[smallest_index]
    list[smallest_index] = temp

  return list

A = [1, 0, 1, 1]
B = [0, 1, 1, 0]


def sum_of_two_bit_arrays(A, B):

  Asum = 0
  Bsum = 0
  Csum = 0
  C = [0] * (len(A) + 1)

  for i in range(len(A)):
    Asum += A[i] * (2 ** i)

  for i in range(len(B)):
    Bsum += B[i] * (2 ** i)

  Csum = Asum + Bsum

  for i in range(len(C)):
    C[i] = Csum % 2
    Csum = Csum // 2

  return C

sum_of_two_bit_arrays(A, B)



"""Add to sum of bit from two list

start with the last number on the list and assign that as the starting index.

moving up an index moves up the exponent by the same rate.

each index from right to left increments the exponent by 1

"""